### ISSUE TITLE
avalon2 的 master 版本

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon2#27]
avalon项目中已经有1.5.4了
avaon2里的master 版本的版本号还只是1.5.3

是忘记修改版本号了吗? 还是avalon2里的master版本就是1.5.3?

按照理解 avalon2里的master版本应该是目前"最新"的版本啊, 新版本的新功能新特性都是加到这个版本里吧.
所以就"版本号"来说 avalon2里的master的版本号不应该是最新的吗?

**Comment by RubyLouvre** [comment]
不可能，avalon1.5.4都是从avalon2项目中拷贝过去的
