### ISSUE TITLE
1.5.4，dialog组件出现bug

### ISSUE THREAD

**Issue by miniers** [RubyLouvre/avalon2#30]
表现为：打开对话框时，对话框并没有出来，只有当页面发生滚动或者缩放时才能出来，初步定位在dialog组件没有执行$ready方法

**Comment by miniers** [comment]
好吧，刚发先真正的触发原因，因为dialog内的button组件 用到了 ms-if 指令，如果条件为false的话，button组件没有构建，导致父级dialog组件认为子组件没有构建完成，所以没有触发$ready方法。
改为ms-visible来控制就没问题了，囧，
再1.5.3用ms-if是没问题的，为啥到1.5.4就改了

**Comment by miniers** [comment]
重现的话，官方给的第一个例子就可以重现

**Comment by RubyLouvre** [comment]
算了，不搞这个，全部精力投入搞avalon.bootstrap
