### ISSUE TITLE
官方案例运行失败

### ISSUE THREAD

**Issue by sikaco** [RubyLouvre/avalon2#44]
![sw8 v22 a0sm0w 3z86k j](https://cloud.githubusercontent.com/assets/5554734/11265304/52fba128-8ed6-11e5-87f7-b18b6cc5dffd.jpg)
![ubj1a2 slxa 6bfm v zoc](https://cloud.githubusercontent.com/assets/5554734/11265327/6ad0e484-8ed6-11e5-8c41-bcfb0dfe8785.jpg)

以下是正常效果。
http://avalonjs.github.io/zh/bindings/component/component01.png

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon2/commit/ecf5efc4a9f92bf969d73d78604656ced2471583 已修

**Comment by RubyLouvre** [comment]
如果你有多个ms:button组件，每个都有不同的配置对象，你可以使用ms-attr-config来动态生成config的值。

<div ms-repeat=array><ms:button ms-attr-config="opts{{$index}}"></div>
如果你嫌这样麻烦，不想在VM上加这配置对象，还可以使用ms-data-button-a来生成这个值。

<div ms-repeat=array><ms:button ms-data-button-a="$index+ 10"></div>

如果你连这个也不想，那么框架就会在已有的VM链上寻找默认配置对象。比如你的自定义签标的tagName为<ms:dropdown>， 那你在已有VM上定义一个叫ms:dropdown的对象就行了。如果你的自定义标签存在横线，比如ms:color-picker,那么它的默认配置对象 应为ms:colorPicker。
