### ISSUE TITLE
binding.handler is not a function

### ISSUE THREAD

**Issue by anrip** [RubyLouvre/avalon2#47]
在一个论坛webview项目中，升级1.5后随机触发这个警告：
  warning:exception throwed in [avalon.injectBinding]  TypeError: binding.handler is not a function

抛错代码片段分析：
  当执行完 a = binding.getter.apply(0, binding.args) 这一句后，binding 的所有属性会变成 null，
  导致无法进行最终的 binding.handler(a, b)

BUG重现方式：
  多数发生在有数据列表分页的时候，来回点击翻页功能

**Comment by RubyLouvre** [comment]
因为那些节点被移除了，相应的绑定对象也全部变成null，你需要用data-view-cache定义到ms-view 所在的文档上

**Comment by anrip** [comment]
那为何偏偏只有getter的时候发生呢？

**Comment by anrip** [comment]
已经找到问题所在。
if (new Date() - beginTime > 444

当页面内容较多，渲染时间大于444毫秒时，就会出现该问题。可以通过调整页面数据量，或增加回收时间来解决此问题。
