### ISSUE TITLE
cyclic object value

### ISSUE THREAD

**Issue by doocal** [RubyLouvre/avalon2#59]
1.4.7 正常，升级到 1.5.5 - 1.5.6 报异常如图(cyclic object value) 说循环引用，检查代码未发现问题。

![f_ r1hmrs q 8jf k 2h](https://cloud.githubusercontent.com/assets/2017549/11713959/8526e170-9f71-11e5-8bcf-5dfbeba518b7.png)

**Comment by RubyLouvre** [comment]
没有看到图
