### ISSUE TITLE
还是内存泄露问题

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon2#60]
最新版avalon.shim和最新版的mmstate结合使用，切换页面的时候会出现内存泄漏。
换回1.4+的avalon版本就没有问题了。
调试的时候发现vm $up引用中的很多对象都没有被释放，还没找到具体原因

**Comment by lkiarest** [comment]
rejectDisposeQueue方法中有一个循环不知道是不是有问题：
```
for (var k = 0, list; list = lists[k++]; ) {
     avalon.Array.remove(lists, list)
    avalon.Array.remove(list, data)
 } //rejectDisposeQueue()方法///////// 遍历的时候删除元素， 遍历顺序是不是要倒序？？
```

**Comment by lkiarest** [comment]
![oom](https://cloud.githubusercontent.com/assets/2672975/11761390/cb80ac88-a0fb-11e5-934e-378494c1530f.png)

**Comment by lkiarest** [comment]
![oom](https://cloud.githubusercontent.com/assets/2672975/11779146/3f3d2e50-a294-11e5-9528-879bb5f75a25.png)
vm里面的list数组中的对象会狂增长，切换一段时间后绑定的一个doLogin方法已经加了62个对象到数组里了，而且对象里的东东都是一样的。。。其他属性也一样，如果是复杂的页面估计受不了啊

**Comment by RubyLouvre** [comment]
估计是
https://github.com/RubyLouvre/avalon2/commit/471baa7315b5a2d27237630d0920f585483da723#diff-a0f1701912fed19677b013d667d2e3a2L1885

```javascript
-            data.uniqueNumber = ++disposeCount
+           data.uniqueNumber = "_"+(++disposeCount)
```
引发的，已经修复
