### ISSUE TITLE
tap事件有问题

### ISSUE THREAD

**Issue by cocotyty** [RubyLouvre/avalon2#62]
![kk](https://cloud.githubusercontent.com/assets/2241753/11975611/8d96f582-a9aa-11e5-8da3-b2cf665da47f.jpg)
![ss](https://cloud.githubusercontent.com/assets/2241753/11975610/8d956140-a9aa-11e5-8717-c0316981f795.jpg)
代码写错了，改成这样就行了

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/78f8b864e45395e5510a2ec8a4f63fffad5e3c0c
