### ISSUE TITLE
新版组件，如果内部有双工绑定，且手动触发改变过一次值，则dom从页面移除的时候不触发组件的$dispose回调

### ISSUE THREAD

**Issue by yyqhlw** [RubyLouvre/avalon2#68]
目前在项目中使用，希望尽快答复或者解决，谢谢

**Comment by roscoe054** [comment]
可以看一下大概代码么

**Comment by yyqhlw** [comment]
var test = avalon.define({
	$id:'test',
	data:{
			parentText:'',
			parentId:'',
			archiveId:'',
			keyId:'',
			name:'234',
			number:0,
			description:'',
			id:''
	},
	$form:{
			
	}
})


	$('#add').click(function(){
		$('body').append('<div id="test" ms-controller="test"><ms:form $id="buildcategoryform" config="$form"><div slot="content"><input ms-duplex="data.name" data-duplex-observe="false" type="text" /></div></ms:form></div>');
		avalon.scan();
	})

	$('#del').click(function(){
		$('#test').remove()
	})

**Comment by yyqhlw** [comment]
大概就是上面的意思， 配合最新版的mmRouter也存在这个问题。如果一个state下有一个组件，且组件里面有双工绑定的东西，且触发过变化。切换状态的时候不触发组件的$dispose回调。话说能不能加个QQ，我给你发demo， 加过几次群，没通过

**Comment by roscoe054** [comment]
@yyqhlw 直接发我邮箱就好啦

**Comment by yyqhlw** [comment]
请问有收到昨天的demo吗

**Comment by roscoe054** [comment]
@yyqhlw 没有收到啊... heiwu805@hotmail.com

**Comment by yyqhlw** [comment]
新的邮箱有收到demo么？

**Comment by roscoe054** [comment]
已收到，确实有这个问题 @RubyLouvre

**Comment by yyqhlw** [comment]
嗯，确实是的。 因为我们的项目功能比较复杂。所以大部分功能必须调用完后销毁以提高性能。
但是遇到这个问题比较辣手...

**Comment by RubyLouvre** [comment]
已经好了

**Comment by yyqhlw** [comment]
还有类似情况发生，出现在有radio绑定的情况下

**Comment by yyqhlw** [comment]
感觉新版组件系统生命周期不太稳定

**Comment by yyqhlw** [comment]
总是会出现找不到组件vmodels的情况
